### ISSUE TITLE
Reconcile the post-refactor Luna gate audit into the canonical r2 work ledger

### ISSUE THREAD

**Issue by 3E4B54** [plasmon-cloud/plasmon#345]
## Classification

- Type: Integration / testing-ledger reconciliation
- Desire: High
- Effort: Low
- Area: Integration / Testing
- Target: `release/0.1.0-r2`

## Observation / problem

The 2026-08-18 post-refactor Luna A/B/C/D audits show that the core r2 regression net survived, but gate promotion is not complete. The lane summaries disagree in detail because Luna D independently reclassified the 42-contract corpus and reports **10 MISSING** contracts, while some lane audit artifacts are currently only present in local worktrees/not inspectable from the remote branches.

A train worker must not need Coordinator chat history or access to another agent's local worktree to know what remains. Every actionable post-refactor finding must therefore be made durable in GitHub and mapped to exactly one canonical Issue/restoration owner.

This Issue owns **ledger reconciliation only**. It does not implement the Product/test gaps itself and must not become a duplicate umbrella implementation Issue.

## Current known mapping

At creation time, Coordinator reconciliation has identified:

- #93 — canonical Product Issue remains open; current r2 still uses `object-fit: cover`, and the packaged geometry gate is also missing.
- #110 — canonical open Issue owns the missing installed hidden-file toggle/reopen/reload persistence proof.
- #81 — canonical open Testing Issue owns the missing composed taskbar lifecycle regression; eligibility remains blocked by #72 acceptance.
- #175 — still RED and actively owned by PR #337.
- #66 browser acceptance — quarantined/restoration owner #320.
- #86 browser acceptance — quarantined/restoration owner #330.
- #63 browser acceptance — restoration owner #308.
- #118 browser acceptance — restoration owner #303.
- sibling Explorer/window-lifetime readiness — restoration owner #251.
- #124 saved-preview acceptance — restoration owner #304.
- #113 packaged Text parity protection — new dedicated backfill Issue #344 because #113 itself is already closed.
- #180 — canonical open Issue owns the missing installed denied-fullscreen Photos acceptance.
- #114 — canonical open Product Issue remains genuinely RED for Markdown formatter/command behavior.
- #100 — canonical open Integration Issue owns the missing dependency-metadata migration/verifier and remains externally blocked on native GitHub dependency mutation capability.
- #87 — canonical open Issue owns the unresolved migration/provenance acceptance decision and permanent migration/preservation coverage.
- #184 / #185 — existing Product Issues already own TaskManager and Show Desktop; they are not new gate-promotion Issues and are currently targeted r2-or-later rather than being invented by this audit.

This list is not allowed to silently substitute for the full Luna-D table; the complete 42-contract result must be reconciled once the new audit artifacts are remotely accessible.

## Scope

- Make the final Luna A/B/C/D post-refactor audit artifacts accessible from durable remote repository state or copy their complete actionable tables into GitHub comments if an artifact is intentionally not promoted.
- Reconcile Luna D's 42-contract master table against the current live r2 source, Issues, PRs, required CI inventory, and quarantine ledger.
- For every `MISSING`, `STILL RED`, or `QUARANTINED` entry, identify exactly one canonical open Issue that owns the remaining work.
- Create a new Issue only when no existing canonical owner exists; do not clone open Product/restoration Issues.
- For closed historical Product Issues whose implementation is accepted but regression protection is missing, use a bounded testing-backfill Issue (as with #344 for #113) instead of silently reopening architecture work.
- Correct any audit classification contradicted by current source. Example: #93 is not test-only while current r2 still has `object-fit: cover`.
- Record `SUPERSEDED` rationale where a historical RED packet should never be promoted.
- Ensure all newly created Issues contain explicit acceptance criteria and `/triage` metadata.
- Ensure workers can discover the remaining work from GitHub alone without needing Coordinator chat or local Luna worktrees.

## Out of scope

- Implementing Product fixes or browser tests from this Issue.
- Merging/rebasing Luna historical TDD branches wholesale.
- Treating historical `.red` files as production tests merely to reduce the missing count.
- Creating duplicate Issues when an existing canonical Issue already owns the exact acceptance gap.
- Removing quarantine without the dedicated restoration Issue's required proof.

## Acceptance criteria

- [x] The final A/B/C/D post-refactor audit artifacts are remotely inspectable or their complete actionable contents are durably reproduced in GitHub.
- [x] All 42 Luna-D contracts are reconciled against the current `release/0.1.0-r2` graph rather than an old audit SHA only.
- [x] Every `MISSING` contract maps to exactly one open canonical Issue, with a newly created Issue only when no existing owner exists.
- [x] Every `STILL RED` Product contract maps to its canonical Product Issue and is not misclassified as test-only promotion work.
- [x] Every `QUARANTINED` browser contract maps to its dedicated restoration Issue and remains executable debt in the canonical quarantine inventory.
- [x] Every `SUPERSEDED` contract has a concrete rationale showing why it should not be promoted.
- [x] Existing open Issues receive the post-refactor audit evidence needed for train workers to understand the remaining acceptance boundary.
- [x] Any new Issues have explicit scope/out-of-scope, acceptance criteria, target, and `/triage` metadata.
- [x] No Product/refactor implementation is duplicated solely because the historical Luna file was not merged verbatim.
- [x] The final reconciliation comment/table can be used by `train.py`/workers without access to Coordinator conversation history or local agent worktrees.

## Verification

Spot-check at least one Desktop/FileManager, Shell/Windowing, Native Apps, metadata/integration, and quarantined-browser contract against live GitHub/source. Confirm that a worker following only the resulting GitHub ledger can reach the correct Issue and acceptance criteria.

## Relationships

- Source audits: Luna A/B/C/D post-refactor promotion audits.
- #344 is the first newly created orphaned backfill found by this reconciliation.
- #295 remains the canonical r2 flaky/quarantine ledger; this Issue must not replace it.

**Comment by 3E4B54** [comment]
## Source audit summaries captured from Coordinator handoff

Audited release SHA: `c047aa7391046dc28efc4d187f8871bb0de4afd2`.

### Luna A — Desktop / FileManager / Filesystem
Artifact: `apps/plasmon/test/tdd/luna-a-post-refactor-promotion-audit.md`
Commit reported: `cea4c002`

- PERMANENT 10
- EQUIVALENT 6
- PACKAGED 8
- QUARANTINED 2
- MISSING 2
- STILL RED 1
- SUPERSEDED 4

Reported gaps: #93 thumbnail geometry; #110 packaged hidden-file persistence; #175 still RED; #66/#320 and #86/#330 quarantined.

### Luna B — Shell / Windowing / Taskbar
Artifact: `apps/plasmon/test/tdd/luna-b-post-refactor-promotion-audit.md`

- PERMANENT 5
- EQUIVALENT 10
- PACKAGED 4
- QUARANTINED 5
- MISSING 2
- STILL RED 2
- SUPERSEDED 1

Reported gaps: missing composed headless taskbar lifecycle regression #81/#198; Product #184 TaskManager and #185 Show Desktop; quarantined #63/#308, #118/#303, sibling/window-lifetime #251, and #43-related browser acceptance.

### Luna C — Native Apps / Editors / Games / Media
Artifact: `apps/plasmon/test/tdd/luna-c-post-refactor-promotion-audit.md`
Commit reported: `e4204f37`

- PERMANENT 2
- EQUIVALENT 10
- PACKAGED 10
- QUARANTINED 1
- MISSING 2
- STILL RED 1
- SUPERSEDED 1

Reported gaps: #113 packaged Text parity assertions; #180 packaged denied-fullscreen Photos acceptance; #114 Product still RED; #124/#304 quarantined.

### Luna D — independent cross-lane audit
Artifact: `apps/plasmon/test/tdd/r2-post-refactor-red-gate-audit.md`

- TOTAL 42
- PERMANENT 15
- EQUIVALENT 6
- PACKAGED 7
- QUARANTINED 3
- MISSING 10
- STILL RED 0
- SUPERSEDED 1

Reported emphasis: core net survived but promotion remains incomplete, especially #100 metadata verifier, #87 migration coverage, editor affordance coverage, and quarantined browser contracts.

These summaries are durable here so a worker can begin reconciliation even before every local audit artifact is pushed. The full tables remain required by this Issue's acceptance criteria because the aggregate classifications differ and must be resolved contract-by-contract.

**Comment by 3E4B54** [comment]
## Coordinator A release-blocking interpretation

Coordinator decision: **the post-refactor gate program is release-blocking for r2**. The primary purpose of r2 is to complete the presentation refactor with the intended regression net actually active; a missing or quarantined meaningful refactor-preservation contract is therefore not ordinary follow-up debt.

Operational rule for this reconciliation:

- `MISSING` accepted/refactor-preservation contracts must map to an r2 `release-blocker` owner.
- `QUARANTINED` accepted/refactor-preservation contracts must map to an r2 `release-blocker` restoration owner until restored to required execution.
- `STILL RED` canonical refactor work remains release-blocking until accepted or deliberately removed from r2 scope by Coordinator decision.
- `SUPERSEDED` is the only normal way a historical Luna gate can leave the blocking set without being promoted; the rationale must be explicit and evidence-backed.
- Merely mapping a missing gate to a low-priority/future Issue is insufficient.

Known owners now explicitly marked `release-blocker` include #344/#345, #93, #110, #81 (and prerequisite #72), #175, #180, the remaining canonical refactor Issues #193/#194/#197/#112/#200/#201, and quarantine/restoration owners #320/#330/#308/#303/#251/#304/#279. #87 was already a release-blocker.

#345 itself may close once the ledger is complete and every actionable contract is routed correctly; the underlying release-blocker owners remain open until their actual gate/product acceptance is complete.

**Comment by 3E4B54** [comment]
## Luna corpus ownership reconciliation at current r2

Reconciled against `origin/release/0.1.0-r2` SHA `028aca8c6fbe2eda446ba0b7932129adf8e14e14` using direct test/source comparison and live Issue/PR inspection.

New bounded owners for orphaned Luna-only r2 contracts:

- #366 — #174 canonical native `.sys` Search regression coverage: exactly-one native projection, hidden-system exclusion, filesystem identity preservation, and canonical activation.
- #367 — #182 user-directory deletion persistence: create/rename/delete a user root directory and prove neither old nor renamed path is resurrected after recomposition.

Existing owners reaffirmed:

- #81 — external/stale Window teardown must reconcile Process state before the next taskbar projection; the existing #72 prerequisite remains authoritative.
- #100 — deterministic dependency-validator fixtures and live queue/dependency eligibility validator; remains blocked on native GitHub dependency mutation capability.
- #110 — packaged Show Hidden Files toggle/reopen/reload proof; PR #352 remains open and nonterminal.
- #93 — packaged thumbnail geometry proof plus Product correction; PR #357 remains open/draft and nonterminal.
- #184/#185 — valid Product RED contracts, but existing Issues target r2-or-later (`0.1.0-r3` currently) and are outside current r2 certification; no release-blocker was invented.

No historical Luna test file was promoted merely because its path was absent. Existing canonical owners were reused where the actual assertion was already owned; only #366 and #367 lacked an open exact owner.

**Comment by 3E4B54** [comment]
## Full-corpus reconciliation at exact current r2

Reconciled against `origin/release/0.1.0-r2` SHA `028aca8c6fbe2eda446ba0b7932129adf8e14e14`, not the older `c047aa7` audit snapshot.

Using a normalized union of the A/B/C post-refactor contract rows, D42 rows not otherwise represented, current required/quarantine boundary contracts, and explicitly retained removed-test/audit contracts, the current full Luna corpus is **105 contract entries**. Classification counts are:

- PERMANENT: 21
- EQUIVALENT: 15
- PACKAGED: 28
- PENDING: 21
- QUARANTINED: 8
- FUTURE: 7
- SUPERSEDED: 5

The normalized entries include the full D42 identity set, not only the 42 rows: retained executable/RTL/browser contracts, prose-only browser boundaries, removed-test obligations, characterization/audit contracts, and split deterministic vs packaged/quarantined contracts where they are materially distinct. The canonical manifest Issue #368 must encode the stable IDs and make this normalization auditable rather than relying on this comment.

Current-r2 PENDING owners are existing #45/#107, #81, #87, #93, #100, #110, #111/#112, #114, #115, #180, #193/#194/#197, #200/#201, #344, #366, and #367 as applicable to their distinct contract rows. Current QUARANTINED owners are #279, #251, #303, #304, #308, #320, and #330 (with split left/right or product/browser rows where applicable). FUTURE owners include #38, #94, #119, #122, #127, #184, and #185. Historical SUPERSEDED entries retain concrete rationale and are not silently counted as green.

New governance owners:

- #368 — checked-in full-corpus manifest, deterministic verifier, and status.sh integration;
- #369 — independent final certification requiring both `Original Luna-D 42/42` and `Full Luna corpus 105/105`.

#345 remains reconciliation/ownership routing; #368 and #369 are bounded follow-on governance work, not Product implementation umbrellas.

**Comment by 3E4B54** [comment]
## Count correction — removed/audit contracts included

The prior comment\047s `105` count was the normalized live A/B/C/D row union plus selected current boundary entries, but it did not yet include every deduplicated intentionally removed/invalid/superseded packet contract required by the full-corpus rule.

After adding the unique removed-test/audit-contract identities from the Luna-A invalid/superseded index, Luna-C invalid registry, and Luna-D invalid packet registry (while deduplicating repeated #66/#173/#178/#182/#190/#175 records), and retaining the #197 cross-lane handoff rationale, the corrected full manifest target is **N=128**:

- PERMANENT: 21
- EQUIVALENT: 15
- PACKAGED: 28
- PENDING: 21
- QUARANTINED: 8
- FUTURE: 7
- SUPERSEDED: 28

The earlier 105-entry live-contract subset remains useful provenance, but #368 must implement and #369 must certify the complete 128-entry corpus. The 28 SUPERSEDED entries are not green evidence; each requires the concrete rationale and replacement/owner metadata specified by #368.

**Comment by 3E4B54** [comment]
## QUARANTINED count correction — #305 is terminal PERMANENT policy evidence

Direct inspection of exact r2 SHA `028aca8c6fbe2eda446ba0b7932129adf8e14e14` confirms that #305 must not be counted as ordinary `QUARANTINED` debt.

Evidence:

- `test/ci/QUARANTINED_BROWSER_TESTS.md` contains exactly seven active `@r2-quarantine` test acceptances, restored by #279, #251, #308, #303, #304, #320, and #330.
- `test/e2e/plasmon-browser-health.ts` allows only the exact full `console.warn` message: `An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.`
- The rule is `kind: "console.warn"` plus exact `message`; it is not a substring or broad sandbox-warning allowance.
- `BrowserHealthLedger` keeps all unmatched console warnings/errors, page errors, failed first-party requests, and HTTP failures fatal.
- `apps/plasmon/test/browserHealthHarness.test.ts` covers fail-closed defaults and narrow allow-rule audit evidence.
- `test/ci/verify-plasmon-test-inventory.mjs` requires the #305 link, exact message, and rejects `messageIncludes: "sandbox"`.
- Issue #305 is CLOSED after reviewed PR #307 and repeated packaged evidence recorded in its terminal closure comment.

Therefore the corrected 128-row totals are:

- PERMANENT: 22
- EQUIVALENT: 15
- PACKAGED: 28
- PENDING: 21
- QUARANTINED: 7
- FUTURE: 7
- SUPERSEDED: 28

The seven actual excluded required-browser gates remain `QUARANTINED` until their restoration owners provide the required unquarantined evidence. Final certification must still require active `@r2-quarantine` count = 0; #305 is not an exemption for any tagged test.

**Comment by 3E4B54** [comment]
Disposition: **CLOSE_SATISFIED**.

I rechecked the complete live Issue/comments, merged PR #349, revalidation PR #392 and its review, and current `release/0.1.0-r2` ledger `apps/plasmon/test/LUNA_POST_REFACTOR_RECONCILIATION.md`.

Evidence against #345 acceptance:
- durable remote A/B/C/D provenance is recorded, including the remotely inspectable historical lane artifacts and the later actionable summaries durably reproduced on #345;
- the current ledger contains the complete 42-contract Luna-D reconciliation against current r2/live GitHub state, not merely the old audit SHA;
- each current `MISSING`, `STILL RED`, and active `QUARANTINED` contract is routed to one canonical owner; orphaned closed-Product regression gaps were bounded into #344/#366/#367 rather than reopening architecture work;
- the seven active required-browser quarantines are explicitly mapped to #279/#251/#308/#303/#304/#320/#330, while #305 is correctly terminal policy evidence rather than skipped-test debt;
- historical `SUPERSEDED` rows carry concrete non-promotion rationale, and the ledger explicitly distinguishes superseded packet evidence from live Product ownership;
- new reconciliation owners #366/#367 and governance follow-ons #368/#369 are durable GitHub Issues, while #345 remains only the routing authority and does not duplicate their implementation/certification scope;
- PR #392 merged the current-r2 revalidation after substantive review; the ledger remains present on `release/0.1.0-r2` and provides worker-facing owner/rationale routing without Coordinator chat or local worktrees.

The later full-corpus manifest/verifier (#368) and exact-SHA certification (#369) are deliberately separate bounded follow-ons and are not unmet #345 acceptance. All #345 criteria are therefore proven; I am checking them and closing the Issue.
